-- !Ups
CREATE TABLE CLOTH
(
    ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME     TEXT,
    PRICE    REAL,
    TYPE_ID  INTEGER,
    BRAND_ID INTEGER,
    FOREIGN KEY (TYPE_ID) references CLOTH_TYPE (ID),
    FOREIGN KEY (BRAND_ID) references BRAND(ID)
);

-- !Downs
DROP TABLE CLOTH;
